In [2]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.4.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (1.22.0rc1)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.

In [3]:
import pandas as pd

In [4]:
data={
    "Brand":["logitech","logitech","apple"],
    "Model": ["MX keys","G915 TKL","Magic Keyboard"],
    "TKL": [False,True,False]
}
df=pd.DataFrame(data)
df
type(df)

pandas.core.frame.DataFrame

## importing data

In [11]:
movie_df=pd.read_csv("new_movie.csv")
movie_df.head()
movie_df["Title"]
# select as a data frame
type(movie_df[["Title","Distributor"]])
# select row using loc
movie_df.iloc[0]
# filtering
movie_df.loc[movie_df["Distributor"]=="Walt Disney Studios Motion Pictures"]

,...1,Title,Movie Info,Distributor,date,year,domestic_sales,international_sales,total_sales,Genre,Movie Runtime,License
0,0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,December 16,2015.0,936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,April 24,2019.0,858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,NaN,700426566,647171407,1347597973,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,NaN,678815482,1369544272,2048359754,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
8,8,The Avengers (2012),Earth's mightiest heroes must come together an...,Walt Disney Studios Motion Pictures,April 25,2012.0,623357910,895457605,1518815515,"['Action', 'Adventure', 'Sci-Fi']",2 hr 23 min,PG-13
...,...,...,...,...,...,...,...,...,...,...,...,...
891,891,Mr. Holland's Opus (1995),A frustrated composer finds fulfillment as a h...,Walt Disney Studios Motion Pictures,NaN,NaN,82569971,23700000,106269971,"['Drama', 'Music']",2 hr 23 min,NaN
896,896,Bridge to Terabithia (2007),A preteen's life turns upside down when he bef...,Walt Disney Studios Motion Pictures,NaN,NaN,82272442,55314621,137587063,"['Drama', 'Family', 'Fantasy']",1 hr 36 min,NaN
902,902,Eight Below (2006),Brutal cold forces two Antarctic explorers to ...,Walt Disney Studios Motion Pictures,February 17,2006.0,81612565,38843429,120455994,"['Adventure', 'Drama', 'Family']",2 hr,PG
909,909,Snow Dogs (2002),When a Miami dentist inherits a team of sled d...,Walt Disney Studios Motion Pictures,January 18,2002.0,81172560,33862530,115035090,"['Adventure', 'Comedy', 'Family', 'Sport']",1 hr 39 min,PG
911,911,While You Were Sleeping (1995),A hopelessly romantic Chicago Transit Authorit...,Walt Disney Studios Motion Pictures,April 21,1995.0,81057016,101000000,182057016,"['Comedy', 'Drama', 'Romance']",1 hr 43 min,PG

In [14]:
# Sort data frame
movie_df.sort_values("domestic_sales",ascending=False)

,...1,Title,Movie Info,Distributor,date,year,domestic_sales,international_sales,total_sales,Genre,Movie Runtime,License
0,0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,December 16,2015.0,936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,April 24,2019.0,858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,December 16,2009.0,760507625,2086738578,2847246203,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,NaN,700426566,647171407,1347597973,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,NaN,678815482,1369544272,2048359754,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
913,913,The Notebook (2004),A poor yet passionate young man falls in love ...,New Line Cinema,June 25,2004.0,81001787,36813370,117815157,"['Drama', 'Romance']",2 hr 3 min,PG-13
914,914,Jimmy Neutron: Boy Genius (2001),An eight-year-old boy genius and his friends m...,Paramount Pictures,December 21,2001.0,80936232,22056304,102992536,"['Action', 'Adventure', 'Animation', 'Comedy',...",1 hr 22 min,NaN
915,915,Eat Pray Love (2010),A married woman realizes how unhappy her marri...,Sony Pictures Entertainment (SPE),August 13,2010.0,80574010,124020006,204594016,"['Biography', 'Drama', 'Romance']",2 hr 13 min,PG-13
916,916,The Texas Chainsaw Massacre (2003),After picking up a traumatized young hitchhike...,New Line Cinema,October 17,2003.0,80571655,26792250,107363905,"['Crime', 'Horror']",1 hr 38 min,R
917,917,Zookeeper (2011),A group of zoo animals decide to break their c...,Sony Pictures Entertainment (SPE),July 6,2011.0,80360843,89491916,169852759,"['Comedy', 'Family', 'Fantasy', 'Romance']",1 hr 42 min,PG

In [15]:
# append new observation
new_movie={
    "Title": "Shingekino",
    "Movie Info": "Titans",	
    "Distributor": "Japan",
    "date": "2013.4.11",	
    "year": "2013",	
    "domestic_sales": "1",
    "international_sales": "2",
    "total_sales": "3",
    "Genre": ["adventure"],	
    "Movie Runtime": "24",	
    "License": "PG13"
}
movie_df.append(new_movie,ignore_index=True)

/var/folders/8z/m4kbswp17qq4hy08by5m6m800000gn/T/ipykernel_64720/3112905634.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  movie_df.append(new_movie,ignore_index=True)

,...1,Title,Movie Info,Distributor,date,year,domestic_sales,international_sales,total_sales,Genre,Movie Runtime,License
0,0.0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,December 16,2015.0,936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1.0,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,April 24,2019.0,858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2.0,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,December 16,2009.0,760507625,2086738578,2847246203,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,3.0,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,NaN,700426566,647171407,1347597973,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,4.0,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,NaN,678815482,1369544272,2048359754,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
914,914.0,Jimmy Neutron: Boy Genius (2001),An eight-year-old boy genius and his friends m...,Paramount Pictures,December 21,2001.0,80936232,22056304,102992536,"['Action', 'Adventure', 'Animation', 'Comedy',...",1 hr 22 min,NaN
915,915.0,Eat Pray Love (2010),A married woman realizes how unhappy her marri...,Sony Pictures Entertainment (SPE),August 13,2010.0,80574010,124020006,204594016,"['Biography', 'Drama', 'Romance']",2 hr 13 min,PG-13
916,916.0,The Texas Chainsaw Massacre (2003),After picking up a traumatized young hitchhike...,New Line Cinema,October 17,2003.0,80571655,26792250,107363905,"['Crime', 'Horror']",1 hr 38 min,R
917,917.0,Zookeeper (2011),A group of zoo animals decide to break their c...,Sony Pictures Entertainment (SPE),July 6,2011.0,80360843,89491916,169852759,"['Comedy', 'Family', 'Fantasy', 'Romance']",1 hr 42 min,PG
918,NaN,Shingekino,Titans,Japan,2013.4.11,2013,1,2,3,[adventure],24,PG13

In [16]:
# delete row
movie_df.drop(2)

,...1,Title,Movie Info,Distributor,date,year,domestic_sales,international_sales,total_sales,Genre,Movie Runtime,License
0,0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,December 16,2015.0,936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,April 24,2019.0,858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,NaN,700426566,647171407,1347597973,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,NaN,678815482,1369544272,2048359754,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
5,5,Spider-Man: No Way Home (2021),"With Spider-Man's identity now revealed, Peter...",Sony Pictures Entertainment (SPE),NaN,NaN,675813257,868642706,1544455963,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 28 min,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
913,913,The Notebook (2004),A poor yet passionate young man falls in love ...,New Line Cinema,June 25,2004.0,81001787,36813370,117815157,"['Drama', 'Romance']",2 hr 3 min,PG-13
914,914,Jimmy Neutron: Boy Genius (2001),An eight-year-old boy genius and his friends m...,Paramount Pictures,December 21,2001.0,80936232,22056304,102992536,"['Action', 'Adventure', 'Animation', 'Comedy',...",1 hr 22 min,NaN
915,915,Eat Pray Love (2010),A married woman realizes how unhappy her marri...,Sony Pictures Entertainment (SPE),August 13,2010.0,80574010,124020006,204594016,"['Biography', 'Drama', 'Romance']",2 hr 13 min,PG-13
916,916,The Texas Chainsaw Massacre (2003),After picking up a traumatized young hitchhike...,New Line Cinema,October 17,2003.0,80571655,26792250,107363905,"['Crime', 'Horror']",1 hr 38 min,R
917,917,Zookeeper (2011),A group of zoo animals decide to break their c...,Sony Pictures Entertainment (SPE),July 6,2011.0,80360843,89491916,169852759,"['Comedy', 'Family', 'Fantasy', 'Romance']",1 hr 42 min,PG